version: '3'
services:
  fa-nginx: 
    links:
      - financial-advisor-nestjs
      - fa-auth-service
    depends_on:
      - financial-advisor-nestjs
      - fa-auth-service

  financial-advisor-nestjs:
    container_name: financial-advisor-nestjs
    environment:
      - CORS_BASE_URL=${CORS_BASE_URL}
      - EXCHANGE_RATES_PROVIDER_APP_ID=${EXCHANGE_RATES_PROVIDER_APP_ID}
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
      - PROVIDER_API_TOKEN=${PROVIDER_API_TOKEN}
      - PROVIDER_BASE_URL=${PROVIDER_BASE_URL}
      - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    links:
      - fa-mongo
      - fa-redis
    depends_on:
      - fa-mongo
      - fa-redis

  fa-auth-service:
    image: "hectorgomezv1/auth-service:${FA_AUTH_SERVICE_IMAGE_RELEASE}"
    ports:
      - "4200:4200"
    environment:
      - ACTIVATION_CODE_EXPIRATION=${FA_AUTH_SERVICE_ACTIVATION_CODE_EXPIRATION}
      - BASE_EMAIL=${FA_AUTH_SERVICE_BASE_EMAIL}
      - BASE_URL=${FA_AUTH_SERVICE_BASE_URL}
      - CORS_BASE_URL=${FA_AUTH_SERVICE_CORS_BASE_URL}
      - FA_AUTH_SERVICE_IMAGE_RELEASE=${FA_AUTH_SERVICE_IMAGE_RELEASE}
      - JWT_SECRET=${FA_AUTH_SERVICE_JWT_SECRET}
      - MONGO_CONNECTION_STRING=${FA_AUTH_SERVICE_MONGO_CONNECTION_STRING}
      - MONGO_DATABASE_NAME=${FA_AUTH_SERVICE_MONGO_DATABASE_NAME}
      - PORT=${FA_AUTH_SERVICE_PORT}
      - REFRESH_TOKEN_EXPIRATION=${FA_AUTH_SERVICE_REFRESH_TOKEN_EXPIRATION}
      - RESET_PASSWORD_CODE_EXPIRATION=${FA_AUTH_SERVICE_RESET_PASSWORD_CODE_EXPIRATION}
      - SENDGRID_API_KEY=${FA_AUTH_SERVICE_SENDGRID_API_KEY}
      - SUPERADMIN_EMAIL=${FA_AUTH_SERVICE_SUPERADMIN_EMAIL}
      - SUPERADMIN_PASSWORD=${FA_AUTH_SERVICE_SUPERADMIN_PASSWORD}
      - TOKEN_EXPIRATION=${FA_AUTH_SERVICE_TOKEN_EXPIRATION}
    links:
      - fa-mongo
    depends_on:
      - fa-mongo

  fa-frontend:
    ports:
      - "9000:9000"
    links:
      - financial-advisor-nestjs
    depends_on:
      - financial-advisor-nestjs

  fa-mongo:
    image: mongo:5-focal
    ports:
      - "27017:27017"
    command: [--auth]
    volumes:
      - mongo_data:/data/db

  fa-redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
  fa_logs:
